In [6]:
import torch

logits = torch.rand([2, 3, 4])
labels = torch.rand([2, 3])
_, _, vocab_size = logits.size()
shift_logits = logits[..., :-1, :].contiguous()
shift_labels = labels[..., 1:].contiguous()
shift_masks = (shift_labels < 0.1).to(shift_logits.device)
entropy = (shift_logits.softmax(dim=-1) * shift_logits.log_softmax(dim=-1)).sum(dim=-1)
entropy.masked_fill_(shift_masks, 0.0)
print(entropy)
print(shift_masks)
entropy = entropy.sum(dim=-1) / ((shift_labels >= 0.1).to(shift_logits.device).long().sum(dim=-1) + 1e-8)
extra_shift_masked = torch.logical_or(entropy < 0.1, entropy > 0.2)
shift_labels.masked_fill_(extra_shift_masked.unsqueeze_(-1).expand_as(shift_labels), 0)
print(logits)
print(labels)
print(entropy)

tensor([[-1.3556, -1.3459],
        [-1.3270, -1.3427]])
tensor([[False, False],
        [False, False]])
tensor([[[0.0505, 0.6576, 0.7591, 0.6015],
         [0.9383, 0.2244, 0.3725, 0.4482],
         [0.0947, 0.4370, 0.7206, 0.8842]],

        [[0.8502, 0.0149, 0.9956, 0.5176],
         [0.3966, 0.7876, 0.1989, 0.0151],
         [0.6792, 0.0646, 0.5737, 0.3498]]])
tensor([[0.1462, 0.5462, 0.5731],
        [0.7030, 0.9634, 0.6472]])
tensor([-1.3507, -1.3348])
